import path from 'path';
import { promises as fs } from 'fs';
import { FileSystemUtils } from '../utils/file-system.js';
import { validateChangeName } from '../utils/change-utils.js';

export interface QuickCommandOptions {
  noRecord?: boolean;
  verify?: boolean;
}

function compactDate(date = new Date()): string {
  return date.toISOString().slice(0, 10).replace(/-/g, '');
}

function requestToSlug(request: string): string {
  const slug = request
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .split('-')
    .filter(Boolean)
    .slice(0, 6)
    .join('-');

  return slug || 'change';
}

export function deriveQuickChangeName(request: string, date = new Date()): string {
  return `quick-${compactDate(date)}-${requestToSlug(request)}`;
}

function buildQuickMarkdown(request: string, changeName: string, verify: boolean): string {
  return `## Request

${request}

## Mode

- Record: yes
- Verify requested: ${verify ? 'yes' : 'no'}
- Change: ${changeName}

## Escalation Decision

Pending agent review.

## Implementation Summary

Pending.

## Verification

${verify ? 'Verification requested. The agent should run a lightweight relevant check when one can be inferred.' : 'No verification requested by default quick mode.'}

## Notes

Generated by \`blockspec quick\`. Continue with \`/opsx:do\` and reuse this quick record.
`;
}

function buildTasksMarkdown(verify: boolean): string {
  const verificationTask = verify
    ? 'Run a lightweight relevant verification check and record the result'
    : 'Record that no verification was requested unless a check becomes necessary';

  return `## 1. Quick Implementation

- [ ] 1.1 Confirm the request is suitable for quick mode
- [ ] 1.2 Locate the affected files
- [ ] 1.3 Implement the requested change
- [ ] 1.4 ${verificationTask}
- [ ] 1.5 Update quick.md with the implementation summary
`;
}

export class QuickCommand {
  async execute(request: string | undefined, options: QuickCommandOptions = {}): Promise<void> {
    const normalizedRequest = request?.trim();
    if (!normalizedRequest) {
      throw new Error('Missing required argument <request>');
    }

    if (options.noRecord) {
      console.log('Quick mode: no record will be created.');
      console.log();
      console.log('Agent handoff:');
      console.log(`/opsx:do "${normalizedRequest}" --no-record${options.verify ? ' --verify' : ''}`);
      if (options.verify) {
        console.log('Verification requested: ask the agent to run one lightweight relevant check if it can infer one.');
      }
      return;
    }

    const projectRoot = process.cwd();
    const changeName = deriveQuickChangeName(normalizedRequest);
    const validation = validateChangeName(changeName);
    if (!validation.valid) {
      throw new Error(validation.error);
    }

    const changeDir = path.join(projectRoot, 'openspec', 'changes', changeName);
    try {
      const stats = await fs.stat(changeDir);
      if (stats.isDirectory()) {
        throw new Error(`Quick change '${changeName}' already exists at ${changeDir}`);
      }
      throw new Error(`Quick change path '${changeDir}' exists and is not a directory`);
    } catch (error: any) {
      if (error.code !== 'ENOENT') {
        throw error;
      }
    }

    await FileSystemUtils.writeFile(
      path.join(changeDir, 'quick.md'),
      buildQuickMarkdown(normalizedRequest, changeName, Boolean(options.verify))
    );
    await FileSystemUtils.writeFile(
      path.join(changeDir, 'tasks.md'),
      buildTasksMarkdown(Boolean(options.verify))
    );

    console.log(`Created quick change '${changeName}' at openspec/changes/${changeName}/`);
    console.log('Created quick.md and tasks.md');
    console.log();
    console.log('Agent handoff:');
    console.log(`/opsx:do "Continue quick change ${changeName}: ${normalizedRequest}"${options.verify ? ' --verify' : ''}`);
  }
}
